#### Q1.  


In [2]:
import numpy as np

A = np.array([
    [12,5,8,20],
    [7,15,3,11],
    [25,9,18,6],
    [10,14,2,16],
])


1 . calculate mean of each row .

In [3]:
rowMean = A.mean(axis = 1)
print(rowMean)

[11.25  9.   14.5  10.5 ]


2. Replace every element that is greater than its row mean by 1. 
3. Replace every other element by 0. 

In [4]:
binary =(A>rowMean [:,np.newaxis]).astype(int)
print(binary)

[[1 0 0 1]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]


4. Return the resulting binary matrix. 

In [5]:
print(binary)

[[1 0 0 1]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]


5. Also determine which row contains the maximum number of elements 
above its row mean.

In [6]:
count = binary.sum(axis=1)
print(count)

[2 2 2 2]


### Q2.

In [7]:
import numpy as np

x = np.array([
    [10,100,5],
    [12,110,6],
    [11,105,7],
    [13,500,6],
    [14,108,8],
    [15,115,9],
])

1. Calculate the mean and standard deviation. 

In [8]:
mean = x.mean(axis=0)
std = x.std(axis=0)

print("Mean :  ",mean)
print("Std: ",std)

Mean :   [ 12.5        173.           6.83333333]
Std:  [  1.70782513 146.31017281   1.34370962]


2. Identify values satisfying: 
∣x−μ∣>2σ 

In [9]:
outlier=np.abs(x-mean)>2*std
print(outlier)

[[False False False]
 [False False False]
 [False False False]
 [False  True False]
 [False False False]
 [False False False]]


3.Replace such values with the corresponding column median.

In [10]:
median = np.median(x,axis=0)
print("mediam: ",median)

mediam:  [ 12.5 109.    6.5]


4. Do this without modifying non-outlier values.

In [11]:
xClean=np.where(outlier,median,x)
print(xClean)

[[ 10. 100.   5.]
 [ 12. 110.   6.]
 [ 11. 105.   7.]
 [ 13. 109.   6.]
 [ 14. 108.   8.]
 [ 15. 115.   9.]]


### Q3.

In [12]:

import pandas as pd  
df = pd.DataFrame({ 'Student': ['A','B','C','D','E','F','G','H'],  
'Department': ['CSE','CSE','ECE','ECE','CSE','ECE','CSE','ECE'],  
'Gender': ['F','M','F','M','M','F','F','M'],  
'Marks': [85,72,91,65,78,88,95,70], 
'Attendance': [92,81,96,72,85,90,98,75] }) 

1.Average marks for each department. 

In [13]:
avgMarks=df.groupby('Department')['Marks'].mean()
print(avgMarks)

Department
CSE    82.5
ECE    78.5
Name: Marks, dtype: float64


2. Average marks separately for each (Department, Gender) group.

In [14]:
avg_Dept_Gen = df.groupby(['Department','Gender'])['Marks'].mean()
print(avg_Dept_Gen)

Department  Gender
CSE         F         90.0
            M         75.0
ECE         F         89.5
            M         67.5
Name: Marks, dtype: float64


3. Student with the highest marks in each department.

In [15]:
HigestMarks = df.loc[df.groupby('Department')['Marks'].idxmax()]
print(HigestMarks)

  Student Department Gender  Marks  Attendance
6       G        CSE      F     95          98
2       C        ECE      F     91          96


4. Students whose marks are above their department average.

In [16]:
deptAvg = df.groupby('Department')['Marks'].transform('mean')
aboveAverage= df[df['Marks']>deptAvg]
print(aboveAverage)

  Student Department Gender  Marks  Attendance
0       A        CSE      F     85          92
2       C        ECE      F     91          96
5       F        ECE      F     88          90
6       G        CSE      F     95          98


5. Department having the highest average attendance.

In [17]:
avgAttendance = df.groupby('Department')['Attendance'].mean()
print(avgAttendance)

Higest_attendance_dept = avgAttendance.idxmax()
print("Dept with higest average attendance is:",Higest_attendance_dept)

Department
CSE    89.00
ECE    83.25
Name: Attendance, dtype: float64
Dept with higest average attendance is: CSE


### Q4.


In [18]:
df = pd.DataFrame({ 'ID': [101,102,103,101,104,102,105],  
'Name': ['A','B','C','A','D','B','E'], 
'Age': [20,21,22,20,23,21,24],  
'Score': [80,75,90,85,88,75,92] })  
print(df)

    ID Name  Age  Score
0  101    A   20     80
1  102    B   21     75
2  103    C   22     90
3  101    A   20     85
4  104    D   23     88
5  102    B   21     75
6  105    E   24     92


1. Identify duplicate ID's

In [19]:
duplicateId = df[df['ID'].duplicated(keep= False)]['ID'].unique()
print(duplicateId)

[101 102]


2. For each ID, determine whether its records are identical. 

In [20]:
for id in duplicateId:
    records = df[df['ID']==id]
    identical= records.drop(columns=['ID']).drop_duplicates().shape==1

    print(f"ID{id}:{'Identical' if identical else 'not identical'}")

ID101:not identical
ID102:not identical


3. If multiple records exist for an ID, retain the record having the highest 
Score.

In [22]:
clean_df = df.sort_values('Score', ascending=False).drop_duplicates(
    subset='ID',
    keep='first'
)
clean_df = clean_df.sort_values('ID').reset_index(drop=True)

4. Produce a clean DataFrame containing exactly one record per ID.

In [23]:
print("\nClean DataFrame:")
print(clean_df)


Clean DataFrame:
    ID Name  Age  Score
0  101    A   20     85
1  102    B   21     75
2  103    C   22     90
3  104    D   23     88
4  105    E   24     92


5. Report how many records were removed. 

In [24]:
records_removed = len(df) - len(clean_df)
print("\nRecords removed:", records_removed)


Records removed: 2


### Q5.

In [40]:
import pandas as pd
df = pd.DataFrame({
    'date' : [
        '2026-01-01',
        '2026-01-02',
        '2026-01-04',
        '2026-01-05',
        '2026-01-08',
        '2026-01-09'
    ],
    'sales' : [100,120,150,130,180,200]
})

1. Convert Date into a proper datetime column.

In [41]:
df['date'] = pd.to_datetime(df['date'])
df = df.set_index('date')

2. Detect the missing dates. 

In [42]:
full_date = pd.date_range(
    start=df.index.min(),
    end=df.index.max(),
    freq='D'
)
missing_date = pd.Index(full_date).difference(pd.Index(df.index))
print("Missing dates :")
print(missing_date)

Missing dates :
DatetimeIndex(['2026-01-03', '2026-01-06', '2026-01-07'], dtype='datetime64[us]', freq=None)


3. Reindex the DataFrame to contain every date between the minimum and 
maximum date.

In [43]:
df = df.reindex(full_date)

4. Keep missing sales as NaN.

In [44]:
print("dataFrame after reindexing:")
print(df)

dataFrame after reindexing:
            sales
2026-01-01  100.0
2026-01-02  120.0
2026-01-03    NaN
2026-01-04  150.0
2026-01-05  130.0
2026-01-06    NaN
2026-01-07    NaN
2026-01-08  180.0
2026-01-09  200.0


5. Calculate a 3-day rolling average of sales. 

In [45]:
df['Rolling_Avg'] = df['sales'].rolling(
    window=3,
    min_periods=1
).mean()

print("\nDataFrame with rolling average:")
print(df)


DataFrame with rolling average:
            sales  Rolling_Avg
2026-01-01  100.0        100.0
2026-01-02  120.0        110.0
2026-01-03    NaN        110.0
2026-01-04  150.0        135.0
2026-01-05  130.0        140.0
2026-01-06    NaN        140.0
2026-01-07    NaN        130.0
2026-01-08  180.0        180.0
2026-01-09  200.0        190.0


6. Identify the date on which the rolling average is maximum.

In [46]:
max_date = df['Rolling_Avg'].idxmax()
max_value = df['Rolling_Avg'].max()

print("\nMaximum rolling average:")
print("Date:", max_date)
print("Rolling Average:", max_value)


Maximum rolling average:
Date: 2026-01-09 00:00:00
Rolling Average: 190.0


### Q6.

In [47]:
import numpy as np

P = np.array([
    [1, 2],
    [4, 6],
    [7, 3],
    [2, 8],
    [9, 5]
])

diff = P[:, np.newaxis, :] - P[np.newaxis, :, :]

D = np.sqrt(np.sum(diff ** 2, axis=2))

print("Distance Matrix:")
print(D)

i, j = np.unravel_index(np.argmax(D), D.shape)

print("\nMaximum distance:", D[i, j])
print("Pair of points:", i + 1, "and", j + 1)
print("Points:", P[i], "and", P[j])

Distance Matrix:
[[0.         5.         6.08276253 6.08276253 8.54400375]
 [5.         0.         4.24264069 2.82842712 5.09901951]
 [6.08276253 4.24264069 0.         7.07106781 2.82842712]
 [6.08276253 2.82842712 7.07106781 0.         7.61577311]
 [8.54400375 5.09901951 2.82842712 7.61577311 0.        ]]

Maximum distance: 8.54400374531753
Pair of points: 1 and 5
Points: [1 2] and [9 5]


### Q7.
